import type { Metadata } from "next";
import "./globals.css";
import BootstrapClient from "../components/BootstrapClient";
import SideBar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="d-flex">
          <SideBar></SideBar>
          <div className="content">{children}</div>
        </div>
      </body>

      <BootstrapClient />
    </html>
  );
}
